from typing import Protocol, Iterable
from uuid import UUID
from .dto import UserDTO

class UserRepoPort(Protocol):
    def add(self, dto: UserDTO) -> None: ...
    def list(self) -> Iterable[UserDTO]: ...
    def get(self, user_id: UUID) -> UserDTO | None: ...
