---
name: Frontend CI (Reusable)

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"
      image-tag:
        required: true
        type: string
      push-image:
        required: false
        type: boolean
        default: false
      registry:
        required: false
        type: string
        default: ghcr.io/ORG
    secrets:
      REGISTRY_USERNAME:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install deps
        run: |
          cd frontend
          npm ci
      - name: Lint
        run: |
          cd frontend
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install deps & test
        run: |
          cd frontend
          npm ci
          npm test -- --ci --reporters=default --reporters=jest-junit

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login registry (optional)
        if: ${{ inputs.push-image == true }}
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | podman login "${{ inputs.registry }}" \
            -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          podman build \
            -f frontend/Containerfile \
            -t "${{ inputs.registry }}/reseau-web:${{ inputs.image-tag }}" \
            frontend

      - name: Scan image (Trivy)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ inputs.registry }}/reseau-web:${{ inputs.image-tag }}
          format: table
          timeout: 10m

      - name: Push image
        if: ${{ inputs.push-image == true }}
        run: |
          podman push "${{ inputs.registry }}/reseau-web:${{ inputs.image-tag }}"
