version: "3.9"

services:
  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data  # named volume (OK Windows)

  redis:
    image: docker.io/library/redis:7-alpine
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  mongo:
    image: docker.io/library/mongo:7.0
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_DATABASE: app

  backend:
    image: localhost/template_projet-backend:dev
    entrypoint: ["/usr/local/bin/backend-entrypoint.sh"]
    environment:
      PYTHONUNBUFFERED: "1"
      DJANGO_SETTINGS_MODULE: app.settings
      DATABASE_URL: postgres://app:app@db:5432/app
      SECRET_KEY: dev-secret
      DEBUG: "1"
      ALLOWED_HOSTS: "*"
      PYTHONPATH: /app/backend/src
      REDIS_URL: redis://redis:6379/0
      MONGO_URL: mongodb://mongo:27017
    volumes:
      - ../../backend:/app/backend
    ports: ["8000:8000"]
    depends_on: [db, redis, mongo]


  web:
    image: localhost/template_projet-web:dev
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    volumes:
      - ../../web:/app/web                 # <-- CORRIGÉ
      - /app/web/node_modules              # volume anonyme pour node_modules
    ports: ["3000:3000"]
    command: sh -lc "cd /app/web && npm run dev"
    depends_on: [backend]

volumes:
  pgdata:
