---
version: "3.9"

services:
  db:
    image: docker.io/postgres:16
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-MyStrongPwd123!}
      POSTGRES_DB: socialdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social"]
      interval: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432"

  api:
    image: ghcr.io/gc69720/reseau-api:${API_TAG:-stage}
    depends_on:
      - db
    env_file:
      - ../../.env.stage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 10
    ports:
      - "8000"

  web:
    image: ghcr.io/gc69720/reseau-web:${WEB_TAG:-stage}
    depends_on:
      - api
    ports:
      - "80"

  nginx:
    image: docker.io/library/nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./infra/podman/nginx/html:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  db_data:
