name: ci
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

jobs:
  app-ci:
    uses: GC69720/social_ci-cd/.github/workflows/python-django.yml@v1
    with:
      python_version: "3.12"
      working_directory: "."          # ou "backend"
      run_tests: true
      django_settings_module: ""      # ex: "app.settings" quand tu auras Django
      docker_image_name: ""           # active plus tard pour builder une image
