name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Permissions nécessaires si tu ajoutes des steps (ici conservées pour homogénéité)
permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  app-ci:
    uses: GC69720/social_ci-cd/.github/workflows/python-django.yml@v1
    with:
      python_version: "3.12"
      working_directory: "."
      run_tests: false            # <— pas de tests dans le repo de templates
      upload_test_artifacts: false
      django_settings_module: ""  # aucun Django ici
      enable_codeql: false        # garde à false pour un vert rapide
      docker_image_name: ""       # pas de build image dans le repo de templates
