name: container-security

on:
  workflow_call:
    inputs:
      image:
        description: "Image à scanner (ex: ghcr.io/org/app:tag). Vide = scan FS uniquement."
        type: string
        default: ""
      path:
        description: "Chemin à scanner (FS)."
        type: string
        default: "."
    secrets: {}

permissions:
  contents: read
  security-events: write

jobs:
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: ${{ inputs.path }}
          format: 'sarif'
          output: 'trivy-fs.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs.sarif

  trivy-image:
    if: ${{ inputs.image != '' }}
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ inputs.image }}
          format: 'sarif'
          output: 'trivy-image.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-image.sarif
