name: oci-sbom-sign

on:
  workflow_call:
    inputs:
      image: { type: string, required: true }
      generate_spdx: { type: boolean, default: true }
      sign_image: { type: boolean, default: false }  # <-- défaut: pas de signature pour stabiliser
    secrets: {}

jobs:
  sbom-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SBOM (Anchore sbom-action)
        if: ${{ inputs.generate_spdx }}
        uses: anchore/sbom-action@v0
        with:
          image: ${{ inputs.image }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        if: ${{ inputs.generate_spdx }}
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom.spdx.json
          retention-days: 7

      - name: Install Cosign
        if: ${{ inputs.sign_image }}
        uses: sigstore/cosign-installer@v3.7.0

      - name: Cosign sign (keyless OIDC)
        if: ${{ inputs.sign_image }}
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign --yes ${{ inputs.image }}

      - name: Cosign verify
        if: ${{ inputs.sign_image }}
        run: cosign verify ${{ inputs.image }} | head -n 50 || exit 1
