name: Release (templates)

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Optional note"
        required: false
        default: ""

permissions:
  contents: read
  packages: write

jobs:
  noop:
    name: No-op release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo "Release workflow for templates repository (no build here)."
          echo "Note: ${{ github.event.inputs.note }}"
