name: secret-scan

on:
  workflow_call:
    secrets: {}

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks scan (container)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # analyser l'historique complet

      # Utilise l'image officielle du projet Gitleaks sur GHCR (pas de nom de personne)
      - name: Run Gitleaks (detect)
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/repo" \
            -w /repo \
            ghcr.io/gitleaks/gitleaks:latest \
            detect --no-banner --redact --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
