name: secret-scan

on:
  workflow_call:
    secrets: {}
permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nécessaire pour scanner l'historique
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2.3.7
        with:
          # default config embarquée; ajoute gitleaks.toml si besoin d'exceptions
          redact: "true"
